# Generated by Django 5.2.5 on 2026-01-15 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_filemodel_name_alter_filemodel_snippet_and_more'),
        ('compendiums', '0005_alter_cardmodel_name_alter_cardmodel_snippet_and_more'),
        ('explorers', '0003_alter_journeymodel_snippet_alter_routemodel_snippet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeymodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='journeymodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='tripmodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tripmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AddIndex(
            model_name='sectionmodel',
            index=models.Index(condition=models.Q(('is_public', True)), fields=['is_public', 'id'], name='sectionmodel_public_idx'),
        ),
    ]
