# Generated by Django 5.2.5 on 2026-01-15 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_filemodel_name_alter_filemodel_snippet_and_more'),
        ('compendiums', '0005_alter_cardmodel_name_alter_cardmodel_snippet_and_more'),
        ('explorers', '0004_alter_journeymodel_name_alter_journeymodel_snippet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackmodel',
            index=models.Index(condition=models.Q(('is_public', True)), fields=['is_public', 'id'], name='trackmodel_public_idx'),
        ),
    ]
