# Generated by Django 5.2.5 on 2026-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0004_alter_cardmodel_snippet_alter_poimodel_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='name',
            field=models.CharField(help_text='A unique name for the object. Must be between 3 and 128 characters long and can include letters, digits, spaces, or special characters such as -, _, and spaces. This field does not serve as a unique identifier within the application but helps users differentiate it from other objects.', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, verbose_name='Snippet'),
        ),
    ]
